# Cria novo contexto

POST http://localhost:3000/contextos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c3VhcmlvIjoxLCJub21lIjoiRmVybmFuZG8gU2lsdmEgTWFyYW5zYXR0byIsImVtYWlsIjoiZmVybmFuZG8ubWFyYW5zYXR0b0BnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRBVTExLmZ2cjJ2TThrcFgvV1hQV1hPeUdjYldyZEhwc1ZpWW1DSTJWOVRBQXgyY3FqTmE2LiIsImlhdCI6MTU4ODkwOTMyOH0.TvBQp6lubPxZl8l4SoOerhmcwMuEK3QaR9oomqhykec

{
    "nome": "Família"
}

### 

# Retorna todos os contextos
GET http://localhost:3000/contextos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c3VhcmlvIjoyLCJub21lIjoiRmVybmFuZG8gU2lsdmEgTWFyYW5zYXR0byIsImVtYWlsIjoiZmVybmFuZG8ubWFyYW5zYXR0b0BnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCR5ZFpZdVlPZ29iejR2RFV3WXRsdS5PTmlhNFVSTFBicUZwZUhKOGVRWDU0b3d4Q2V5VldFTyIsImlhdCI6MTU4OTg0MTI2N30.jkVhD5FBMQpBfhmH09KMMaYBRWEWeVYP70gM8ZEKXPk

###


# Retorna todos os contextos
DELETE http://localhost:3000/contextos/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c3VhcmlvIjoxLCJub21lIjoiRmVybmFuZG8gU2lsdmEgTWFyYW5zYXR0byIsImVtYWlsIjoiZmVybmFuZG8ubWFyYW5zYXR0b0BnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRBVTExLmZ2cjJ2TThrcFgvV1hQV1hPeUdjYldyZEhwc1ZpWW1DSTJWOVRBQXgyY3FqTmE2LiIsImlhdCI6MTU4ODkwOTMyOH0.TvBQp6lubPxZl8l4SoOerhmcwMuEK3QaR9oomqhykec

###

# Retorna todas as contas do contexto
GET http://localhost:3000/contextos/25/contas
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c3VhcmlvIjoxLCJub21lIjoiRmVybmFuZG8gU2lsdmEgTWFyYW5zYXR0byIsImVtYWlsIjoiZmVybmFuZG8ubWFyYW5zYXR0b0BnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRBVTExLmZ2cjJ2TThrcFgvV1hQV1hPeUdjYldyZEhwc1ZpWW1DSTJWOVRBQXgyY3FqTmE2LiIsImlhdCI6MTU4ODkwOTMyOH0.TvBQp6lubPxZl8l4SoOerhmcwMuEK3QaR9oomqhykec

### 
