# Altera valor do orçamento
PATCH http://localhost:3000/orcamentos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c3VhcmlvIjoxLCJub21lIjoiRmVybmFuZG8gU2lsdmEgTWFyYW5zYXR0byIsImVtYWlsIjoiZmVybmFuZG8ubWFyYW5zYXR0b0BnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRBVTExLmZ2cjJ2TThrcFgvV1hQV1hPeUdjYldyZEhwc1ZpWW1DSTJWOVRBQXgyY3FqTmE2LiIsImlhdCI6MTU4ODkwOTMyOH0.TvBQp6lubPxZl8l4SoOerhmcwMuEK3QaR9oomqhykec

{
    "id_orcamento" : 2,
    "id_categoria" : 1,
    "valor" : 888
}
###
